version: '3'
services:
  eureka:
    container_name: eureka
    build:
      context: .
      dockerfile: DockerFile.eureka
    image: eureka:latest
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8888/eureka"}}}}'
    expose:
      - 8888
    ports:
      - 8888:8888
    networks:
      - spring-cloud-network
  microService:
    container_name: account-micro-service
    build:
      context: .
      dockerfile: DockerFile.ams
    image: account-micro-service:latest
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8888/eureka"}}}}'
    expose:
      - 2222
    ports:
      - 2222:2222
    networks:
      - spring-cloud-network
    depends_on:
      - eureka
networks:
  spring-cloud-network:
    driver: bridge